global:
  nodeSelector:
    role: infra
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - dev-mkube-argocd.joins.seungdobae.com
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
configs:
  params:
    "server.insecure": true
  cm:
    url: https://dev-mkube-argocd.joins.seungdobae.com
  secret:
    argocdServerAdminPassword: $2a$10$8zswoW14GECMF2aFLryBbOMkSCdSDqpY6w5iCNZC.BYUrrI56zu9K