---
- name: Complements CIS result master
  hosts: kube_control_plane
  tasks:
  - name: 1.1.9 Ensure that the Container Network Interface file permissions are set to 600 or more restrictive
    file:
      path: /etc/cni/net.d
      mode: "600"
      recurse: yes
      state: directory

  - name: 1.1.20 Ensure that the Kubernetes PKI certificate file permissions are set to 600 or more restrictive
    block:
    - name: find *.crt files
      find:
       paths: /etc/kubernetes/pki/
       patterns: '*.crt'
      register: crt_files

    - name: change permission to 600
      file:
        path: "{{ item.path }}"
        mode: "0600"
      loop: "{{ crt_files.files }}"

- name: Complements CIS result Node
  hosts: kube_node
  tasks:
  - name: 4.1.1 Ensure that the kubeadm.conf file permissions are set to 600 or more restrictive
    file:
      path: /etc/systemd/system/kubelet.service
      mode: "600"

  - name: 4.1.7 Ensure that the certificate authorities file permissions are set to 600 or more restrictive
    file:
      path: /etc/kubernetes/ssl/ca.crt
      mode: "600"

  - name: 4.1.9 Ensure that the kubelet-config.yaml file permissions are set to 600
    file:
      path: /etc/kubernetes/kubelet-config.yaml
      mode: "600"

