repositories:
- name: harbor
  url: https://helm.goharbor.io
- name: jenkins
  url: https://charts.jenkins.io

helmDefaults:
  createNamespace: true

releases:
- name: harbor
  namespace: harbor
  chart: harbor/harbor
  version: 1.11.1
  values:
  - ./values/harbor.yaml

- name: jenkins
  namespace: jenkins
  chart: jenkins/jenkins
  version: 4.3.10
  values:
  - ./values/jenkins.yaml
