controller:
  hostNetwork: true
  kind: DaemonSet
  service:
    type: ClusterIP
    targetPorts:
      https: http
  metrics:
    enabled: true
    ServiceMonitor:
      enabled: true
  nodeSelector:
    role: router
