toolbox:
  enabled: true

## 어피니티 스토리지 노드에 배포 
cephClusterSpec:
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker

  cephVersion:
    image: quay.io/ceph/ceph:v17.2.5
  dashboard:
    ssl: false
