apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: spring-boot-actuator-monitor
  namespace: spring-boot-actuator-monitor
spec:
  endpoints:
    - interval: 30s
      path: /actuator/prometheus
      port: actuator-port
  namespaceSelector:
    any: true
  selector:
    matchLabels: # 서비스 라벨
      actuator-prometheus: "true"
