all:
  vars:
    ansible_port: 22
    ansible_user: ubuntu
    ansible_become: yes
  hosts:
    k8s-master-1:
      ansible_host: 10.233.100.10
    k8s-worker-1:
      ansible_host: 10.233.100.20
    k8s-worker-2:
      ansible_host: 10.233.100.21
    k8s-ingress-1:
      ansible_host: 10.233.10.15
  children:
    kube_control_plane:
      hosts:
        k8s-master-1:
    kube_worker:
      hosts:
        k8s-worker-1:
        k8s-worker-2:
        k8s-ingress-1:
      vars:
        node_labels:
          node-role.kubernetes.io/worker: ""
    router: # Ingress 전용 노드 라벨링
      hosts:
        k8s-ingress-1:
      vars:
        node_labels:
          node-role.kubernetes.io/ingress: ""
    etcd:
      hosts:
        k8s-master-1:
    kube_node:
      hosts:
        k8s-master-1:
        k8s-worker-1:
        k8s-worker-2:
        k8s-ingress-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
