## 설정 파일 외부 경로 
kubectl_localhost: true
kubeconfig_localhost: true
artifacts_dir: /kubespray/artifacts/

## 버전 (v1.31.2 - 2025년 기준 안정 버전)
kube_version: v1.31.2
calico_version: v3.28.1
containerd_version: 1.7.22

## Cluster config
kube_network_plugin: calico
kube_proxy_mode: ipvs
container_manager: containerd

# Calico CNI
calico_ipip_mode: Always
calico_vxlan_mode: Never
calico_network_backend: bird
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

# Image GC
kubelet_image_gc_high_threshold: 70
kubelet_image_gc_low_threshold: 60

#########################################################
# Hardening 및 보안 설정 (v1.31 호환) - 주석 처리됨
# authorization_modes: ['Node', 'RBAC']
# kubernetes_audit: true
# audit_log_path: "/var/log/kube-apiserver-log.json"
# audit_log_maxage: 30
# audit_log_maxbackups: 10
# audit_log_maxsize: 100

# TLS 설정
# tls_min_version: VersionTLS12
# tls_cipher_suites:
#   - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
#   - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
#   - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305

# Encryption at rest
# kube_encrypt_secret_data: true

## Admission Plugins
# kube_apiserver_enable_admission_plugins:
#   - EventRateLimit
#   - AlwaysPullImages
#   - ServiceAccount
#   - NamespaceLifecycle
#   - NodeRestriction
#   - LimitRanger
#   - ResourceQuota
#   - MutatingAdmissionWebhook
#   - ValidatingAdmissionWebhook
#   - PodNodeSelector
#   - PodSecurity

## Kubelet 보안
# kubelet_authorization_mode_webhook: true
# kubelet_authentication_token_webhook: true
# kube_read_only_port: 0
# kubelet_rotate_server_certificates: true
# kubelet_protect_kernel_defaults: true
# kubelet_rotate_certificates: true
# kubelet_streaming_connection_idle_timeout: "5m"
# kubelet_make_iptables_util_chains: true
# kubelet_feature_gates: ["RotateKubeletServerCertificate=true", "SeccompDefault=true"]
# kubelet_seccomp_default: true
# kubelet_systemd_hardening: true

# 추가 설정
kube_owner: root
kube_cert_group: root
# kube_pod_security_use_default: true
# kube_pod_security_default_enforce: restricted
