## 설정 파일 외부 경로 
kubectl_localhost: true
artifacts_dir: /kubespray/artifacts/

## 버전  
kube_version: v1.25.6
calico_version: v3.24.5
containerd_Version: 1.6.15

## Cluster confige
kube_network_plugin: calico
kube_proxy_mode: ipvs

# Calico CNI
calico_ipip_mode: Always
calico_vxlan_mode: Never
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

# Image GC
kubelet_image_gc_high_threshold: 70
kubelet_image_gc_low_threshold: 60
